### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by kburns** [glwagner/dedaLES#18]
I started a branch for adding a quick setup.py script to make dedaLES at least locally installable using setup.py and/or pip.  Along with this we probably want to pick a license for the code.  I think this should probably be GPL3 given the reliance on Dedalus, which is GPL3.

**Comment by glwagner** [comment]
That sounds smart to me! 

Feel free to open a PR anytime and we can work on it. Are there any updates to the README and docs we'd like to put in the PR as well?

**Comment by glwagner** [comment]
Should we also migrate the code to an organization?

We could wait on this if we think that the code should, eventually, belong in the 'dedalus' GitHub organization... 😏

**Comment by glwagner** [comment]
@kburns 

Want to make a `dedalus` organization on GitHub? We can add dedaLES to it (even if you aren't ready to migrate the dedalus source yet).

**Comment by kburns** [comment]
We actually have one already (https://github.com/DedalusProject)!  I think we should hold off for now on moving the repo since we haven't decided yet what our general thoughts are regarding hosting the "core" vs "derived" packages there (i.e. what are our responsibilities for maintenance of those packages, standards of acceptance, etc.).

**Comment by glwagner** [comment]
Solved by #22.
